### ISSUE TITLE
Dependency to latest JSDoc3 repo

### ISSUE THREAD

**Issue by mknet** [jannon/JSDoc-JUI#1]
Hey there,

in your README you are explaining that JSDoc-JUI just works with your fork of JSDoc since the original "doesn't quite have what it takes". Since the last update of the README was done a year ago and there was a movement of the repository as well, I am wondering if JSDoc-JUI still doesn't work with the offical version hosted under https://github.com/jsdoc3/jsdoc

I gave it a try myself and got the clue that it doesn't work but I am not really sure. Could you give me a short hint?

Many thanks
Marcel

**Comment by speich** [comment]
I tried it with the latest JSDoc and I didn't get it to work, because of several dependencies on files no longer available or moved to different locations. It would be great if you could update your pretty template to work with the latest version of JSDoc3.
